### ISSUE TITLE
Sabre exception when querying Owncloud calendar

### ISSUE THREAD

**Issue by greyspammer** [tobixen/calendar-cli#15] opened 2015-11-05 18:00 UTC
I'm trying to read a calendar from a local server running Owncloud. The client system is Xubuntu 15.10, the server is Ubuntu 14.04 with Owncloud 8.1.4. I assume that's what the 'agenda' subcommand is supposed to do.

```
$ ./calendar-cli.py calendar agenda
Traceback (most recent call last):
  File "./calendar-cli.py", line 665, in <module>
    main()
  File "./calendar-cli.py", line 662, in main
    ret = args.func(caldav_conn, args)
  File "./calendar-cli.py", line 328, in calendar_agenda
    events_ = find_calendar(caldav_conn, args).date_search(dtstart, dtend)
  File "/usr/local/lib/python2.7/dist-packages/caldav/objects.py", line 491, in date_search
    response = self._query(root, 1, 'report')
  File "/usr/local/lib/python2.7/dist-packages/caldav/objects.py", line 120, in _query
    raise error.exception_by_method[query_method](ret.raw)
caldav.lib.error.ReportError: <?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:sabredav-version>2.1.6</s:sabredav-version>
  <s:exception>Sabre\VObject\EofException</s:exception>
  <s:message>End of document reached prematurely</s:message>
</d:error>
```

Printing the todo list seems to work:

```
 ./calendar-cli.py todo list
2015-11-05! 2016-11-04  Test 1 2 3 4
```

Adding items to the calendar also works. It's just the reading that doesn't work.

I am not sure what to make of this. Other CalDAV clients like the CalDAV sync adapter for Android or Mozilla Thunderbird with the Lightning plugin work just fine.

**Comment by tobixen** [comment] 2015-11-05 18:23
Can you arrange a temporary test account for me at your caldav server?

**Comment by greyspammer** [comment] 2015-11-05 20:09
Can do. I'll send you an e-mail with the access information. Check your inbox (and spam folder).

I also noticed that while calendar-cli claims to successfully add events, they do not appear in the OwnCloud web frontend or Thunderbird/Lightning.

**Comment by tobixen** [comment] 2015-11-05 21:11
Uhm ... sorry, it seems like I didn't get any such email.  Try t-calendar-cli@tobixen.no

**Comment by tobixen** [comment] 2015-11-06 19:33
One small step ahead.  Added support for self-signed certs in calendar-cli and have reproduced the error:

$ calendar-cli --config-section=testissue15 calendar agenda 
Traceback (most recent call last):
  File "/home/tobias/bin/calendar-cli", line 798, in <module>
    main()
  File "/home/tobias/bin/calendar-cli", line 795, in main
    ret = args.func(caldav_conn, args)
  File "/home/tobias/bin/calendar-cli", line 382, in calendar_agenda
    events_ = find_calendar(caldav_conn, args).date_search(dtstart, dtend)
  File "/usr/lib/python2.7/site-packages/caldav-0.4.0-py2.7.egg/caldav/objects.py", line 490, in date_search
    response = self._query(root, 1, 'report')
  File "/usr/lib/python2.7/site-packages/caldav-0.4.0-py2.7.egg/caldav/objects.py", line 123, in _query
    raise error.exception_by_method[query_method](errmsg(ret))
caldav.lib.error.ReportError: 500 Internal Server Error

<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:sabredav-version>2.1.6</s:sabredav-version>
  <s:exception>Sabre\VObject\EofException</s:exception>
  <s:message>End of document reached prematurely</s:message>
</d:error>

**Comment by greyspammer** [comment] 2015-11-06 21:23
JFTR: I updated OwnCloud from 8.1.4 to 8.2 (which also updated Sabre to 2.1.7). But it did not fix the problem:

```
$ ./calendar-cli.py calendar agenda
Traceback (most recent call last):
  File "./calendar-cli.py", line 665, in <module>
    main()
  File "./calendar-cli.py", line 662, in main
    ret = args.func(caldav_conn, args)
  File "./calendar-cli.py", line 328, in calendar_agenda
    events_ = find_calendar(caldav_conn, args).date_search(dtstart, dtend)
  File "/usr/local/lib/python2.7/dist-packages/caldav/objects.py", line 491, in date_search
    response = self._query(root, 1, 'report')
  File "/usr/local/lib/python2.7/dist-packages/caldav/objects.py", line 120, in _query
    raise error.exception_by_method[query_method](ret.raw)
caldav.lib.error.ReportError: <?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:sabredav-version>2.1.7</s:sabredav-version>
  <s:exception>Sabre\VObject\EofException</s:exception>
  <s:message>End of document reached prematurely</s:message>
</d:error>
```

**Comment by tobixen** [comment] 2015-11-09 05:45
Seems like you're not the only one having problems: https://bitbucket.org/cyrilrbt/caldav/issues/48/error-reading-owncloud-calendar

I have other owncloud servers I'm testing towards, so this is weird.

Haven't gotten much time to dig into this during the weekend.

**Comment by tobixen** [comment] 2015-11-13 09:32
Sorry that things are taking time.  I'm having a bit too much work in the pipeline atm.

**Comment by greyspammer** [comment] 2016-01-05 09:18
Sorry to bother you, but are you still working on this?

I understand if you have too much to do at the moment. But if you have given up, I'll shut down the access I gave you to my server. Security and all that.

**Comment by tobixen** [comment] 2016-01-05 09:28
I had big plans to sit down and work with the calendar project during the holidays now, but unfortunately I've had serious issues with pain in my back lately, I just couldn't sit down and work.

All tests breaks consistently with your server, I'm clueless as to why, but I will look into it relatively soon.

**Comment by tobixen** [comment] 2016-04-04 19:25
My back pains are due to an herniated disc.  Still have big problems, but I'll try to work a bit on this calendering mess during the next few weeks.

**Comment by tobixen** [comment] 2017-01-23 18:53
Version 0.5.0 of the caldav library was just released.  Quite some bugfixes made it into that release, so possibly the issue is gone.

I don't have access to any owncloud servers I can test with anymore, hence procrastinating this even further.

**Comment by mcepl** [comment] 2018-01-01 22:25
> I don't have access to any owncloud servers I can test with anymore, hence procrastinating this even further.

What do you need? I have here a bit ancient ``owncloud-7.0.13`` but you can certainly have a testing account. Also, calendar-cli from ``HEAD`` of the ``master`` branch, doesn't see all my TODO items. WOuldn't the information on https://www.davdroid.com/tested-with/ be interesting?

If you want the account let me know on the email I have in my profile.

**Comment by tobixen** [comment] 2020-05-01 11:02
I've been quite swamped during the last years, but planning to put some priority to calendar-cli and the caldav library this month.

I believe this is an issue on the caldav side of things.

Would still need a test account.  I did spend a couple of hours earlier this year to see if I easily could set up a handful of calendar servers, including owncloud, either through creating a puppetized throw-away VM or by setting it up as a docker image, but I gave it up.  My employer has an owncloud installation, but without calendaring as we're using zimbra for that.

**Comment by tobixen** [comment] 2020-05-29 21:09
28 days have passed ... but no, I didn't forget, I've just been prioritizing the caldav library.  Version 0.7.0. was released today, and I can again look into the command line utility.

I've been offered some test accounts for owncloud up through the times, but I don't think I have any test accounts working at the moment.  Installing my own owncloud seems to be a bit too much work right now.  As far as I've understood, owncloud is based on sabre, baikal is also based on sabre, and the caldav library has been tested towards baikal, so things should just work ... hopefully.  The last report that things does not work is from 2015.  Unless someone can tell me that things still doesn't work, I'm inclined to close this issue.

**Comment by tobixen** [comment] 2020-06-05 11:25
I'm giving up and closing this one now; issues encountered on owncloud as of 2015 with old calendar-cli and version 0.5 of the caldav library is likely to have disappeared or changed, I don't have any owncloud server with calendar support to test towards at the moment, and I don't have the capacity to set up anything now.

If anyone experiences that calendar-cli doesn't work towards owncloud, using version 0.7 of the caldav library, then please raise a new issue on it.

**Closed by tobixen** 2020-06-05 11:25 UTC
Labels: bug
