### ISSUE TITLE
missing dependency on requests

### ISSUE THREAD

**Issue by muelli** [tobixen/calendar-cli#17] opened 2016-01-22 11:09 UTC
something's weird after a pip install --upgrade  'git+https://github.com/tobixen/calendar-cli#egg=calendar-cli':

```
>./bin/calendar-cli.py  -h
Traceback (most recent call last):
  File "./bin/calendar-cli.py", line 12, in <module>
    import caldav
  File "/tmp/radicale/local/lib/python2.7/site-packages/caldav/__init__.py", line 3, in <module>
    from .davclient import DAVClient
  File "/tmp/radicale/local/lib/python2.7/site-packages/caldav/davclient.py", line 4, in <module>
    import requests
ImportError: No module named requests
```

I have the feeling it's not necessarily calendar-cli's fault, so the bug might need to be propagated.
In any case, the ".py" suffix could be gotten rid of...

**Comment by tobixen** [comment] 2016-01-22 11:14
I've taken over the maintainer role for the caldav library anyway, so I'll look into it

**Comment by tobixen** [comment] 2016-01-22 11:17
The requests library is included in the install_requires in caldav/setup.py ... so ... basically this shouldn't happen :p

**Comment by tobixen** [comment] 2016-01-22 11:31
I'm not much into package management, pip, easy-install and that.  Someone with the right knowledge should probaby look into this one.

Hm, renaming it from calendar-cli.py to calendar-cli.py ... should probably be done, though I'm concerned of breaking compatibility.  (maybe add a temporary symlink there?)

**Comment by tobixen** [comment] 2017-01-23 18:49
Could not reproduce.  I will close this one as for now.

One thing I noticed, the shebang says the script should be run under python2.  When I do "python ./setup.py install", it invoces python3, and will not install the dependencies.

**Closed by tobixen** 2017-01-23 18:49 UTC

**Comment by tobixen** [comment] 2017-01-23 19:02
(eventually, try to remove the caldav library and reinstall it)
